var config = {
    title: "XX need to update XX",
    imageName: "/current/tmp/image.jpg",
    location: "XX need to update XX",
    latitude: 0,
    longitude: 0,
    az: 0,
    camera: "XX need to update XX",
    computer: "XX need to update XX",
    owner: "TXX need to update XX",
    auroraMap: "XX need to update XX",
    overlaySize: 875,
    overlayOffsetLeft: 0,
    overlayOffsetTop: 0,
    auroraForecast: false,
    showOverlayAtStartup: false,
}
