var config = {
    title: "Whitehorse, YT",
    imageName: "image-resize.jpg",
    location: "Whitehorse",
    latitude: 60.7,
    longitude: -135.05,
    az: 180,
    camera: "ASI224MC",
    computer: "Raspberry Pi 3",
    owner: "Thomas Jacquin",
    auroraMap: "north",
    overlaySize: 875,
    overlayOffsetLeft: 0,
    overlayOffsetTop: 0,
}
